### ISSUE TITLE
Publishing 23.12 on PyPI

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rapids-dask-dependency#12]
Recently `dask-cuda` 23.12 was published to PyPI. Though as it now requires `rapids-dask-dependency`, which doesn't appear to be published for 23.12, the install fails.

Is this expected at this point? If so, when (roughly) do we plan to have `rapids-dask-dependency` published for `23.12`?

**Comment by vyasr** [comment]
I think we'll need @raydouglass to answer that question. For some reason there's a nightly already uploaded to PyPI, but I think that's erroneous: https://pypi.org/project/rapids-dask-dependency/. I'll defer to Ray on the process.

**Comment by jakirkham** [comment]
Discussed with Ray offline. He has since uploaded the package (please see screenshot). Am able to `pip install` without issues. So this appears resolved. Closing...

<img width="1840" alt="Screenshot 2023-12-12 at 3 07 15 PM" src="https://github.com/rapidsai/rapids-dask-dependency/assets/3019665/d258d77b-4778-492b-bee1-1918638964a4">
