### ISSUE TITLE
[Discussion] Include dask-expr dependency for Dask Dataframe?

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/rapids-dask-dependency#23]
The `2024.2.0` release of dask has deprecated the "legacy" `dask.dataframe` API in favor of [dask-expr](https://github.com/dask-contrib/dask-expr). I am already working on a PR to update dask-cudf accordingly (https://github.com/rapidsai/cudf/pull/14805). However, there may be a strange transition period until the dask-expr package is made an explicit dependency of `dask` (or when the dask-expr code is simply copied directly into dask/dask).

Until the dask-expr dependency is handled by dask/dask directly, we may want to include it in `rapids-dask-dependency`. Does it seem reasonable to do this once `20.02` is released?

**Comment by rjzamora** [comment]
As discussed in offline discussion, the current plan is to pin to dask/distributed `2024.1.1` for the remainder of `24.04`. Since we will be adding *optional* (opt-in) dask-expr support for `24.04`, I suggest that we add dask-expr `0.4.0` as a new dependency (should be light weight).

**Comment by vyasr** [comment]
If we include dask-expr but pin to dask 2024.1.1, I assume the result for RAPIDS is a no-op? i.e. it requires dask>2024.1.1 to actually start importing and using dask-expr, so that'll just be an unused package installed onto the system unless someone opts in?

**Comment by rjzamora** [comment]
>If we include dask-expr but pin to dask 2024.1.1, I assume the result for RAPIDS is a no-op? i.e. it requires dask>2024.1.1 to actually start importing and using dask-expr, so that'll just be an unused package installed onto the system unless someone opts in?

No, dask-expr has been an optional API engine for `dask.dataframe` since December-ish. https://github.com/rapidsai/cudf/pull/14805 will be needed to actually take advantage of the option, but that PR should be merged soon.

**Comment by vyasr** [comment]
I think we're on the same page but I misstated a few things. What I means was that dask-expr will be unused _by default_ and will require opting in until we change dask-cudf's default behavior. If we bumped to `dask>2024.1.1` before we updated rapids to support the new expression-based APIs in dask by default, we would start seeing a boatload of warnings, so we have no plan to change that pinning until we also change the default. In practice, that means that when RAPIDS starts supporting `dask>2024.1.1` is also when RAPIDS users will implicitly start using dask-expr. In the interim, users could choose to opt in to dask-expr usage by setting the appropriate dask configuration, but that may break e.g. dask-cudf until rapidsai/cudf#14805 is merged. Is that right?

**Comment by rjzamora** [comment]
Yes, I think you have everything generally correct. Once https://github.com/rapidsai/cudf/pull/14805 is merged, we will be using the dask-expr dependency for tests, but the user would need to opt in themselves to actually use it in practice.

**Comment by vyasr** [comment]
Closing since @rjzamora added dask-expr in #29. Please reopen if I missed something.
