### ISSUE TITLE
Pin RAPIDS `24.04` to `dask-2024.1.1`

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/rapids-dask-dependency#26]
The “legacy” Dask Dataframe API is now deprecated (dask>=2024.2.0). Although dask-cudf can (and should) comfortably support the new API in time for the RAPIDS 24.04 release, other down-stream libraries will not have sufficient time to adjust to this migration.

**Suggestion**: In order to balance both upstream and downstream maintenance risks, we should pin RAPIDS `24.04` to `dask-2024.1.1`.

## Offline discussion

[Link to internal document discussing the plan](https://docs.google.com/document/d/1g6VWflvKuOJlsrFe1GB3wN5ZPB3vUMTYyOa6MXqm1dk/edit?usp=sharing)

## Notes on related Dask releases

Discussion on dask-expr integration timeline: https://github.com/dask/dask/issues/10934

### Dask 2024.1.1
- Date: (Completed) January 26th 2024
- Link: [commit b1909c7](https://github.com/dask/dask/tree/b1909c7719f264bed567b95460593910fb2dedc2)
- No blocking issues known
- Supports optional integration with dask-expr, with partial API coverage

### Dask 2024.2.0
- Date: (Completed) February 9th 2024
- Link: [commit 7726d31](https://github.com/dask/dask/tree/7726d3195e089202c2033027eaf16e227e68fbaf)
- Supports optional integration with dask-expr, with partial API coverage
- Introduces loud deprecation warning for import dask.dataframe
  - https://github.com/dask/dask/issues/10917

### Dask 2024.2.1
- Date: (Planned) February 23rd 2024
- Will introduce a config option to silence the 2024.2.0 deprecation warning
  - https://github.com/dask/dask/pull/10925
- RAPIDS libraries (e.g. dask-cudf) cannot silence the deprecation warning if dask.dataframe is imported first

### Dask 2024.3.0
- Date: (Planned) March 8th 2024
- The “dataframe.query-planning” config default will change to “True” if certain requirements are met (See [#10934](https://github.com/dask/dask/issues/10934) for more info)
- RAPIDS libraries (e.g. dask-cudf) will need to reload dask.dataframe to leverage the “legacy” dask.dataframe API
  - This approach may be fragile. The more reliable solution is to support dask-expr

### Dask X.X.X
- Date: (Planned) Unknown
- The “dataframe.query-planning”: “False” config option will be disabled
- There is not a strong motivation to make this change soon, because Dask Array and Dask Bag still use much of the same `HighLevelGraph` infrastructure as the legacy DataFrame API. However, I strongly suspect that this motivation will grow quickly as soon as there is a clear maintenance burden.

**Comment by rjzamora** [comment]
cc @jakirkham @vyasr @galipremsagar for viz

**Comment by vyasr** [comment]
@rjzamora I think we can close this issue, right? The plan is to keep the pin as discussed, then unpin again for 24.06?

**Comment by rjzamora** [comment]
Thanks for following up @vyasr ! Yes. We can close this, since we are indeed pinned to `dask-2024.1.1` for `24.04`. We can re-open if this plan unexpectedly changes.
